// This file declares the IPreviewHandler Interface and Gateway for Python.
// Generated by makegw.py
// ---------------------------------------------------
//
// Interface Declaration

class PyIPreviewHandler : public PyIUnknown
{
public:
	MAKE_PYCOM_CTOR(PyIPreviewHandler);
	static IPreviewHandler *GetI(PyObject *self);
	static PyComTypeObject type;

	// The Python methods
	static PyObject *SetWindow(PyObject *self, PyObject *args);
	static PyObject *SetRect(PyObject *self, PyObject *args);
	static PyObject *DoPreview(PyObject *self, PyObject *args);
	static PyObject *Unload(PyObject *self, PyObject *args);
	static PyObject *SetFocus(PyObject *self, PyObject *args);
	static PyObject *QueryFocus(PyObject *self, PyObject *args);
	static PyObject *TranslateAccelerator(PyObject *self, PyObject *args);

protected:
	PyIPreviewHandler(IUnknown *pdisp);
	~PyIPreviewHandler();
};
// ---------------------------------------------------
//
// Gateway Declaration

class PyGPreviewHandler : public PyGatewayBase, public IPreviewHandler
{
protected:
	PyGPreviewHandler(PyObject *instance) : PyGatewayBase(instance) { ; }
	PYGATEWAY_MAKE_SUPPORT2(PyGPreviewHandler, IPreviewHandler, IID_IPreviewHandler, PyGatewayBase)



	// IPreviewHandler
	STDMETHOD(SetWindow)(
		HWND hwnd,
		CRECTPTR prc);

	STDMETHOD(SetRect)(
		CRECTPTR prc);

	STDMETHOD(DoPreview)(
		void);

	STDMETHOD(Unload)(
		void);

	STDMETHOD(SetFocus)(
		void);

	STDMETHOD(QueryFocus)(
		HWNDPTR phwnd);

	STDMETHOD(TranslateAccelerator)(
		MSGPTR pmsg);

};
